### ISSUE TITLE
Potentially hitting the EMR rate limit

### ISSUE THREAD

**Issue by ajmssc** [relateiq/azkaban#12]
With the change to allow multiple flows to share clusters, every flow will make api calls to EMR to monitor the spool up. If we have 100 flows waiting for the same cluster, we could hit the EMR rate limit and this will cause exceptions and failures.

We should have a single thread monitor clusters for all flows.

**Comment by tovbinm** [comment]
Can we have the API call limit increase?

**Comment by ajmssc** [comment]
That's a question for @hjdesai2 and @magnusthorne

**Comment by feliperazeek** [comment]
I can easily keep that information in memory to avoid an EMR call

**Comment by feliperazeek** [comment]
https://github.com/relateiq/azkaban/pull/14
